### ISSUE TITLE
📋 [TASK] - Update Pipeline Template Workflow Files

### ISSUE THREAD

**Issue by lizzcondrey** [DevOps-MBSE/.github#13]
### Parent Feature

#12

### Task Description

As an AaC Developer, I want to update the .github workflow files in the .github repository, so that the pipeline templates use the updated build chain.

### Acceptance Criteria

- [ ] Update workflow build files
  - [ ] python-build-and-lint.yml
  - [ ] python-cross-platform-support.yml
- [ ] Need to update workflows that have a pip install or wheel build step to utilize new build chain
