### ISSUE TITLE
📋 [TASK] - Build Chain Corrections in Pipeline Templates

### ISSUE THREAD

**Issue by lizzcondrey** [DevOps-MBSE/.github#25]
### Parent Feature

#12

### Task Description

As an AaC Developer, I need to correct some issues in my workflow templates, so that I provide a consistent and reliable pipeline workflow configuration for my repositories.

### Acceptance Criteria

- [x] Remove package version reference steps and names from cross platform configuration.
- [x] Remove commented out page deployment in main workflow configuration.
- [x] Confirm plugin test step to generic verbiage in cross platform workflow configuration.
