### ISSUE TITLE
📋 [TASK] - Migrate setup-python Action

### ISSUE THREAD

**Issue by lizzcondrey** [DevOps-MBSE/.github#4]
### Parent Feature

#1

### Task Description

As an AaC CI/CD Developer, I want to migrate the setup-python version, so that I have the latest supported pipeline action version.

### Acceptance Criteria

- [x] Migrate versions in python-build-and-lint.yml template workflow
- [x] Migrate versions in python-cross-platform-support.yml template workflow
- [ ] Migrate versions in python-deploy-artifacts.yml template workflow
- [x] Migrate versions in python-test-python-version.yml template workflow

**Helpful Links**

[actions/setup-python: Set up your GitHub Actions workflow with a specific version of Python](https://github.com/actions/setup-python)

[Setup Python · Actions · GitHub Marketplace](https://github.com/marketplace/actions/setup-python)

[setup-python/docs/advanced-usage.md at main · actions/setup-python (github.com)](https://github.com/actions/setup-python/blob/main/docs/advanced-usage.md)
