### ISSUE TITLE
📋 [TASK] - Migrate checkout Action

### ISSUE THREAD

**Issue by lizzcondrey** [DevOps-MBSE/.github#5]
### Parent Feature

#1

### Task Description

As an AaC CI/CD Developer, I want to migrate the checkout version, so that I have the latest supported pipeline action version.

### Acceptance Criteria

- [x] Migrate versions in codeql-analysis.yml template workflow
- [x] Migrate versions in python-build-and-lint.yml template workflow
- [x] Migrate versions in python-cross-platform-support.yml template workflow
- [ ] Migrate versions in python-deploy-artifacts.yml template workflow
- [x] Migrate versions in python-test-python-version.yml template workflow
- [x] Migrate versions in deploy-pages.yml template workflow

**Helpful Links**

[Checkout · Actions · GitHub Marketplace](https://github.com/marketplace/actions/checkout)

[Releases · actions/checkout (github.com)](https://github.com/actions/checkout/releases)

**Examples**

[[Github Actions] actions/checkout@v3 should be upgraded to v4 · Issue #2285 · denoland/fresh](https://github.com/denoland/fresh/issues/2285)
