### ISSUE TITLE
📋 [TASK] - Migrate gh-action-pypi-publish Action to a Release

### ISSUE THREAD

**Issue by lizzcondrey** [DevOps-MBSE/.github#6]
### Parent Feature

#1

### Task Description

As an AaC CI/CD Developer, I want to migrate the gh-action-pypi-publish to a release version, so that I have the latest supported pipeline action version.

### Acceptance Criteria

- [x] Migrate versions in python-deplopy-artifacts.yml template workflow
- [ ] Include dynamic name referencing
  - [ ] Repo and package version

**Helpful Links**

[pypi-publish · Actions · GitHub Marketplace](https://github.com/marketplace/actions/pypi-publish)
